baseURL: "https://medi-train.github.io/" 
title: MediTrain
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 5 
        - name: Team
          url: team/
          weight: 2
        - name: Papers
          url: papers/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Dissemination
          url: dissemination/
          weight: 6

params:
    description: "This website hosts information about HRZZ project MEDITRAIN. "
    author: Marija Habijan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "June 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about","team","papers","data","dissemination"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Medical Education and Planning Through Virtual Reality
          subtitle: |
            The use of extended reality (XR) in medical education and surgical procedure planning brings significant changes to medical practice. Advanced XR systems enable the creation of interactive and realistic simulations, facilitating preparation for complex surgeries and providing additional information during the procedures themselves. Despite rapid technological development, challenges remain related to data availability, generation of synthetic cases, and standardization of education. <br><br>
            This project focuses on developing new methods and systems to enhance medical education and surgical planning using AI and XR. <br><br>

            The goal is to develop innovative methods for education, simulation, and analysis of medical images using machine learning algorithms that will (1) increase doctors' experience regarding placenta accreta and the importance of its examination during pregnancy, thereby reducing the rate of missed cases of placenta accreta detection during ultrasound examination, and (2) increase the ease of execution and quality of cerebrovascular procedures by creating detailed and realistic VR/XR simulations of specific neurosurgical procedures.  <br><br>

            This work was supported by the Croatian Science Foundation under the project number IP-2024-05-9492.
          <div class="profile-images">
            <img src="static/logo.png" width="100" height="100" alt="meditrain">
            <img src="static/ferit.png" width="100" height="100" alt="ferit">
            <img src="static/hrzz_logo_eng.png" width="100" height="100" alt="hrzz">
          </div>

          buttons:
            - name: About
              url: about/
            - name: Team
              url: team/
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Disemination
              url: disemination/



    socialIcons:
        - name: Email
          url: mailto:meditrain2025@gmail.com
        - name: GitHub
          url: https://github.com/medi-train
        - name: ResearchGate
          url: https://pmichaillat.substack.com
        - name: FERIT
          url: https://www.ferit.unios.hr/ 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "MediTrain"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2