baseURL: "https://pascalmichaillat.org/hugo-website/" 
title: MediTrain
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts information about HRZZ project MEDITRAIN. "
    author: Marija Habijan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "June 2025"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Medical Education and Planning Through Virtual Reality
          subtitle: |
            The use of extended reality (XR) in medical education and surgical procedure planning brings significant changes to medical practice.<br><br>
            This project focuses on developing new methods and systems to enhance medical education and surgical planning using AI and XR.
          imageUrl: "hrzz_logo_eng.png"
          imageWidth: 700
          imageHeight: 160
          imageUrl: "hrzz_logo_eng.png"
          buttons:
            - name: About
              url: about
            - name: Papers
              url: papers/
            - name: Data
              url: data/
            - name: Disemination
              url: disemination/


    socialIcons:
        - name: Email
          url: mailto:meditrain2025@gmail.com
        - name: GitHub
          url: https://github.com/medi-train
        - name: ResearchGate
          url: https://pmichaillat.substack.com
        - name: FERIT
          url: https://www.ferit.unios.hr/ 

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "MediTrain"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2